Prevent 'undefined method' error when repository does not have a cleanup policy and now will add one
When 'cleanup_policies' / 'policyName' has never been set on a (new) repository
the insync? check fails with
```
Error: /Stage[main]/Profiles::Service::Nexus/Nexus3_repository[maven-central]/cleanup_policies: change from '' to [] failed: undefined method `sort' for "":String
```
Setting the default to [] resolves this issue.