Prevent 'undefined method' error
When 'cleanup_policies' / 'policyName' has never been set on a (new) repository
the insync? check fails with
```
Error: /Stage[main]/Profiles::Service::Nexus/Nexus3_repository[maven-central]/cleanup_policies: change from '' to [] failed: undefined method `sort' for "":String
```
Setting the default to [] resolves this issue.